### PR TITLE
Update naming convention of repositories

### PR DESCRIPTION
**Pull request by petrnohejl**
I suggest updating the naming convention of repositories and reflecting the fact that several tech departments in STRV manage multiple platforms (e.g. Backend department uses NodeJS and Go platforms). I suggest making the platform keyword mandatory so that everyone knows directly from the repository name what technology is being used.

### CODE REVIEW

**Comment by MichalKlacko** [comment]
isn't the template naming convention missing word "template"? 
I'd expect that

**Comment by petrnohejl** [comment]
`<platform>-<module>` is a general naming formula for any internal repository, therefore I wouldn't mention specific `<module>` there. It can be "template", "snippets", "video-editor", "academy-2022", etc. Perhaps we could add examples of internal repositories so it is more clear?

**Comment by cejanen** [comment]
Our examples
ios-project-template
ios-vse-course-spring2023
ios-snippets

**Comment by petrnohejl** [comment]
@MichalKlacko I added examples of internal repositories including templates.

**Comment by CermakM** [comment]
I am handing over an RFE with my 2 cents below.

```
- Naming formula for projects: `<project>-<platform>-<module>`
- Naming formula for templates and other internal repositories: `<platform>-<module>`
```

First of all, I would propose explicitly mentioning the technology stack, instead of enclosing this into the `platform` part to disambiguate the naming, i.e. `<platform>-<stack>` would be my personal preference, where `stack` is for example `nodejs`, `go`, `flutter`, etc.

Second, I would explicitly mention whether it is an `internal` repo or `template`. This can be logically placed instead of the `<project>` part in my opinion.

An example pattern would be the following pattern (feel free to test it on https://regex101.com):

```
/(?P<project>[A-Za-z]+)-(?P<platform>[A-Za-z]+)-(?P<stack>[A-Za-z]+)[-]?(?P<module>[A-Za-z0-9-]+)?/gm
```

Where the examples might be:

```
internal-mobile-ios-vse-course-spring2023
internal-mobile-ios-snippets
icebreaker-mobile-flutter-app
icebreaker-backend-go-api
icebreaker-infra-aws
internal-frontend-react-authentication-services
template-backend-nodejs-api
```

This way, the `template` part gets replaced by the `project` name when used, we can clearly see internal repositories, and we can distinguish the name of the project and the module. The only disambiguity here is a potentially multi-part project name, which I would prefer not to use, but I'd leave it to the best judgment.

As you may have noticed, I would also introduce `mobile` and `infra|devops` as a platform and `ios`, `kotlin`, `flutter`, `aws`, `gcp`, etc... as the stack.

The module still remains optional.

CC @petrnohejl @MichalKlacko

**Review by CermakM — CHANGES_REQUESTED** [review]
Requesting changes for the reasons mentioned in https://github.com/strvcom/strv-guidelines/pull/3#issuecomment-1647563465

**Comment by petrnohejl** [comment]
I understand your point with ambiguity, on the other hand, this naming convention would lead to unnecessarily long repo names which I personally consider as a bigger disadvantage. I prefer `surge-android` over `surge-mobile-android`. In many cases the `<platform>` part in the name is unnecessary and `<stack>` would be enough, but for example backend managers prefer to keep the `<platform>` part which I respect. Also, what `<platform>` would you choose for the Unity stack? If managers stick to the naming rules, there won't be any ambiguity.

Regarding the internal and template keywords - why should templates have a reserved keyword in the naming formula and other types of repositories (like snippets, courses, docs) not? I think that these special keywords are not necessary. They only lead to unnecessarily long names. I prefer `android-snippets` over `internal-mobile-android-snippets`.

I agree with introducing more platforms/stacks.

**Comment by cejanen** [comment]
@CermakM @petrnohejl 
I kinda agree with Petr. First really don't need mobile for platform, second I don't need internal prefix to realize it's internal repo. First I know it from name (ios as prefix or suffix) second we use for repos topics in settings. It's a way how to have "tags" for repos. We have ios-research, ios-library etc

Screenshot 2023-07-31 at 15 06 54
Screenshot 2023-07-31 at 15 08 30

**Comment by MichalKlacko** [comment]
I think we discussed that module (e.g. nodejs, go, aws etc...) will be optional. As we as Backend need it and mobile don't.

So why not state both examples and make it optional.

```
backend-template-nodejs-api
ios-template
```

So i would do 
\<platform>-template-<*module>

**Comment by petrnohejl** [comment]
@MichalKlacko You are mixing `<platform>`, `<stack>` and `<module>` together. Please see the proposed convention. For example "nodejs" is not a `<module>`, but `<stack>` which is part of the `<platform>`. We don't use `<stack>` in the formula, it was introduced by Marek so I use it now to explain the proposed convention better. Let me explain one more time on your example:

`<platform>-<module>`

`<platform>` is "backend-nodejs"
`<module>` is "template" or can be also "template-api"

So the repository name would be "backend-nodejs-template-api".

As I already said in the previous comment, I don't see any reason why templates should have a reserved keyword in the naming formula. There are so many types of repositories (like snippets, courses, docs). I'd prefer to use a more generic formula for all types of internal repositories. Let me know what you think.

I think that `<stack>` (android, ios, nodejs, go, react, flutter) should be mandatory as it is in my opinion the most important information in the repository name.

**Comment by petrnohejl** [comment]
To make it more clear, I propose to use `<platform>` in the formula rather than `<*department>-<stack>` where `<*department>` is optional to avoid non-determinism.

With `<platform>-<module>` it is always clear that the repo should be named "backend-nodejs-template".

With `<*department>-<stack>-<module>` someone could name it "backend-nodejs-template" and someone else "nodejs-template" which would cause inconsistency which we want to avoid.

**Comment by MichalKlacko** [comment]
Updated: we discussed with Peter and he will update exaples to make it more clear.

**Comment by MichalKlacko** [comment]
I'm ok with proposed examplea/rules. 
Its consistent with current naming and covering all the needs.
@CermakM what do you think?

**Review by CermakM — APPROVED** [review]

**Pull request merged**
